name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11.5  

    - name: Set up Conda environment
      run: conda create --name myenv python=3.11.5
    
    - name: Activate Conda
      run: conda init bash

    - name: Activate environment and install dependencies
      run: |
        conda activate myenv
        pip install .[tests]

    - name: Run tests
      run: pytest tests/  
